export type LanguageSchool = {
  id: string;
  name: string;
  country: string;
  city: string;
  programs: string[];
  duration_weeks_min: number;
  duration_weeks_max: number;
  weekly_cost: number;
  accommodation_weekly?: number;
  rating: number;
  class_size_max: number;
  accreditations: string[];
  facilities: string[];
  visa_difficulty: 'easy' | 'moderate' | 'difficult';
  part_time_work_allowed: boolean;
  pathway_programs: boolean;
  scholarship_available: boolean;
  age_min: number;
};

export const languageSchools: LanguageSchool[] = [
  {
    id: 'ec-london',
    name: 'EC English London',
    country: 'United Kingdom',
    city: 'London',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Cambridge Exam Prep', 'Business English'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 350,
    accommodation_weekly: 250,
    rating: 4.5,
    class_size_max: 15,
    accreditations: ['British Council', 'English UK'],
    facilities: ['Library', 'Computer Lab', 'Student Lounge', 'Free WiFi'],
    visa_difficulty: 'moderate',
    part_time_work_allowed: false,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'kaplan-ny',
    name: 'Kaplan International - New York',
    country: 'United States',
    city: 'New York',
    programs: ['General English', 'Intensive English', 'TOEFL Prep', 'Business English'],
    duration_weeks_min: 2,
    duration_weeks_max: 52,
    weekly_cost: 450,
    accommodation_weekly: 400,
    rating: 4.6,
    class_size_max: 15,
    accreditations: ['ACCET', 'English USA'],
    facilities: ['Computer Lab', 'Student Lounge', 'Library', 'Outdoor Space'],
    visa_difficulty: 'difficult',
    part_time_work_allowed: false,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'ilsc-toronto',
    name: 'ILSC Toronto',
    country: 'Canada',
    city: 'Toronto',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Business English', 'University Pathway'],
    duration_weeks_min: 1,
    duration_weeks_max: 48,
    weekly_cost: 320,
    accommodation_weekly: 220,
    rating: 4.4,
    class_size_max: 16,
    accreditations: ['Languages Canada'],
    facilities: ['Computer Lab', 'Student Lounge', 'Kitchen', 'Free WiFi'],
    visa_difficulty: 'easy',
    part_time_work_allowed: true,
    pathway_programs: true,
    scholarship_available: true,
    age_min: 16
  },
  {
    id: 'els-sydney',
    name: 'ELS Universal English College Sydney',
    country: 'Australia',
    city: 'Sydney',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Cambridge Exam Prep'],
    duration_weeks_min: 1,
    duration_weeks_max: 60,
    weekly_cost: 280,
    accommodation_weekly: 240,
    rating: 4.3,
    class_size_max: 18,
    accreditations: ['NEAS', 'English Australia'],
    facilities: ['Computer Lab', 'Student Lounge', 'Library', 'Kitchen'],
    visa_difficulty: 'moderate',
    part_time_work_allowed: true,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 18
  },
  {
    id: 'lsi-auckland',
    name: 'LSI Auckland',
    country: 'New Zealand',
    city: 'Auckland',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Cambridge Exam Prep'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 300,
    accommodation_weekly: 210,
    rating: 4.5,
    class_size_max: 14,
    accreditations: ['NZQA', 'English New Zealand'],
    facilities: ['Computer Lab', 'Student Lounge', 'Kitchen', 'Free WiFi'],
    visa_difficulty: 'easy',
    part_time_work_allowed: true,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'bcit-dublin',
    name: 'BCIT Dublin',
    country: 'Ireland',
    city: 'Dublin',
    programs: ['General English', 'Business English', 'IELTS Prep', 'Cambridge Exam Prep'],
    duration_weeks_min: 25,
    duration_weeks_max: 52,
    weekly_cost: 160,
    accommodation_weekly: 180,
    rating: 4.2,
    class_size_max: 15,
    accreditations: ['ACELS', 'Quality English'],
    facilities: ['Computer Lab', 'Student Lounge', 'Library', 'Free WiFi'],
    visa_difficulty: 'easy',
    part_time_work_allowed: true,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 18
  },
  {
    id: 'eurocentres-malta',
    name: 'Eurocentres Malta',
    country: 'Malta',
    city: 'St. Julians',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Business English'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 200,
    accommodation_weekly: 150,
    rating: 4.4,
    class_size_max: 14,
    accreditations: ['ELT Council', 'FELTOM'],
    facilities: ['Swimming Pool', 'Computer Lab', 'Student Lounge', 'Rooftop Terrace'],
    visa_difficulty: 'easy',
    part_time_work_allowed: false,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'sprachcaffe-frankfurt',
    name: 'Sprachcaffe Frankfurt',
    country: 'Germany',
    city: 'Frankfurt',
    programs: ['General English', 'Business English', 'IELTS Prep', 'German Language'],
    duration_weeks_min: 1,
    duration_weeks_max: 48,
    weekly_cost: 250,
    accommodation_weekly: 180,
    rating: 4.1,
    class_size_max: 14,
    accreditations: ['EAQUALS', 'ALTO'],
    facilities: ['Computer Lab', 'Student Lounge', 'Garden', 'Free WiFi'],
    visa_difficulty: 'moderate',
    part_time_work_allowed: true,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 18
  },
  {
    id: 'ilac-vancouver',
    name: 'ILAC Vancouver',
    country: 'Canada',
    city: 'Vancouver',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'University Pathway', 'Business English'],
    duration_weeks_min: 2,
    duration_weeks_max: 52,
    weekly_cost: 310,
    accommodation_weekly: 230,
    rating: 4.7,
    class_size_max: 15,
    accreditations: ['Languages Canada', 'ALTO'],
    facilities: ['Computer Lab', 'Student Lounge', 'Kitchen', 'Free WiFi', 'Game Room'],
    visa_difficulty: 'easy',
    part_time_work_allowed: true,
    pathway_programs: true,
    scholarship_available: true,
    age_min: 16
  },
  {
    id: 'kings-boston',
    name: 'Kings Boston',
    country: 'United States',
    city: 'Boston',
    programs: ['General English', 'Intensive English', 'TOEFL Prep', 'University Pathway'],
    duration_weeks_min: 2,
    duration_weeks_max: 52,
    weekly_cost: 420,
    accommodation_weekly: 350,
    rating: 4.5,
    class_size_max: 15,
    accreditations: ['ACCET', 'English USA'],
    facilities: ['Computer Lab', 'Student Lounge', 'Library', 'Sports Facilities'],
    visa_difficulty: 'difficult',
    part_time_work_allowed: false,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'browns-gold-coast',
    name: 'Browns English Gold Coast',
    country: 'Australia',
    city: 'Gold Coast',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Cambridge Exam Prep', 'Barista English'],
    duration_weeks_min: 1,
    duration_weeks_max: 60,
    weekly_cost: 290,
    accommodation_weekly: 220,
    rating: 4.6,
    class_size_max: 16,
    accreditations: ['NEAS', 'English Australia'],
    facilities: ['Computer Lab', 'Student Lounge', 'Kitchen', 'BBQ Area', 'Beach Access'],
    visa_difficulty: 'moderate',
    part_time_work_allowed: true,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'ilsc-brisbane',
    name: 'ILSC Brisbane',
    country: 'Australia',
    city: 'Brisbane',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Cambridge Exam Prep', 'Business English'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 300,
    accommodation_weekly: 230,
    rating: 4.4,
    class_size_max: 15,
    accreditations: ['NEAS', 'English Australia'],
    facilities: ['Computer Lab', 'Student Lounge', 'Kitchen', 'Outdoor Area'],
    visa_difficulty: 'moderate',
    part_time_work_allowed: true,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'ec-cape-town',
    name: 'EC English Cape Town',
    country: 'South Africa',
    city: 'Cape Town',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Business English'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 180,
    accommodation_weekly: 140,
    rating: 4.5,
    class_size_max: 15,
    accreditations: ['IALC', 'SACSA'],
    facilities: ['Computer Lab', 'Student Lounge', 'Rooftop Terrace', 'Free WiFi'],
    visa_difficulty: 'moderate',
    part_time_work_allowed: false,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'ec-manchester',
    name: 'EC English Manchester',
    country: 'United Kingdom',
    city: 'Manchester',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Cambridge Exam Prep'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 320,
    accommodation_weekly: 210,
    rating: 4.3,
    class_size_max: 15,
    accreditations: ['British Council', 'English UK'],
    facilities: ['Computer Lab', 'Student Lounge', 'Library', 'Free WiFi'],
    visa_difficulty: 'moderate',
    part_time_work_allowed: false,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'bsc-york',
    name: 'BSC York',
    country: 'United Kingdom',
    city: 'York',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Cambridge Exam Prep'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 290,
    accommodation_weekly: 190,
    rating: 4.4,
    class_size_max: 12,
    accreditations: ['British Council', 'English UK'],
    facilities: ['Computer Lab', 'Student Lounge', 'Garden', 'Free WiFi'],
    visa_difficulty: 'moderate',
    part_time_work_allowed: false,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'lsi-vancouver',
    name: 'LSI Vancouver',
    country: 'Canada',
    city: 'Vancouver',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Cambridge Exam Prep', 'Business English'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 300,
    accommodation_weekly: 240,
    rating: 4.3,
    class_size_max: 16,
    accreditations: ['Languages Canada'],
    facilities: ['Computer Lab', 'Student Lounge', 'Kitchen', 'Free WiFi'],
    visa_difficulty: 'easy',
    part_time_work_allowed: true,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'ilsc-montreal',
    name: 'ILSC Montreal',
    country: 'Canada',
    city: 'Montreal',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Business English', 'French Language'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 280,
    accommodation_weekly: 200,
    rating: 4.5,
    class_size_max: 15,
    accreditations: ['Languages Canada'],
    facilities: ['Computer Lab', 'Student Lounge', 'Kitchen', 'Free WiFi'],
    visa_difficulty: 'easy',
    part_time_work_allowed: true,
    pathway_programs: true,
    scholarship_available: true,
    age_min: 16
  },
  {
    id: 'kaplan-la',
    name: 'Kaplan International - Los Angeles',
    country: 'United States',
    city: 'Los Angeles',
    programs: ['General English', 'Intensive English', 'TOEFL Prep', 'Business English'],
    duration_weeks_min: 2,
    duration_weeks_max: 52,
    weekly_cost: 440,
    accommodation_weekly: 380,
    rating: 4.5,
    class_size_max: 15,
    accreditations: ['ACCET', 'English USA'],
    facilities: ['Computer Lab', 'Student Lounge', 'Outdoor Area', 'Free WiFi'],
    visa_difficulty: 'difficult',
    part_time_work_allowed: false,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'kaplan-chicago',
    name: 'Kaplan International - Chicago',
    country: 'United States',
    city: 'Chicago',
    programs: ['General English', 'Intensive English', 'TOEFL Prep', 'Business English'],
    duration_weeks_min: 2,
    duration_weeks_max: 52,
    weekly_cost: 430,
    accommodation_weekly: 340,
    rating: 4.4,
    class_size_max: 15,
    accreditations: ['ACCET', 'English USA'],
    facilities: ['Computer Lab', 'Student Lounge', 'Library', 'Free WiFi'],
    visa_difficulty: 'difficult',
    part_time_work_allowed: false,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'ilsc-san-francisco',
    name: 'ILSC San Francisco',
    country: 'United States',
    city: 'San Francisco',
    programs: ['General English', 'Academic English', 'TOEFL Prep', 'Business English', 'University Pathway'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 450,
    accommodation_weekly: 420,
    rating: 4.6,
    class_size_max: 15,
    accreditations: ['ACCET', 'English USA'],
    facilities: ['Computer Lab', 'Student Lounge', 'Kitchen', 'Free WiFi'],
    visa_difficulty: 'difficult',
    part_time_work_allowed: false,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'embassy-melbourne',
    name: 'Embassy English Melbourne',
    country: 'Australia',
    city: 'Melbourne',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Cambridge Exam Prep'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 310,
    accommodation_weekly: 250,
    rating: 4.4,
    class_size_max: 16,
    accreditations: ['NEAS', 'English Australia'],
    facilities: ['Computer Lab', 'Student Lounge', 'Library', 'Kitchen'],
    visa_difficulty: 'moderate',
    part_time_work_allowed: true,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'converse-san-diego',
    name: 'Converse International School San Diego',
    country: 'United States',
    city: 'San Diego',
    programs: ['General English', 'Intensive English', 'TOEFL Prep', 'Business English'],
    duration_weeks_min: 2,
    duration_weeks_max: 52,
    weekly_cost: 360,
    accommodation_weekly: 310,
    rating: 4.3,
    class_size_max: 12,
    accreditations: ['ACCET', 'English USA'],
    facilities: ['Computer Lab', 'Student Lounge', 'Garden', 'Beach Access'],
    visa_difficulty: 'difficult',
    part_time_work_allowed: false,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'gv-hawaii',
    name: 'Global Village Hawaii',
    country: 'United States',
    city: 'Honolulu',
    programs: ['General English', 'Intensive English', 'TOEFL Prep', 'Business English'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 380,
    accommodation_weekly: 350,
    rating: 4.7,
    class_size_max: 14,
    accreditations: ['ACCET', 'English USA'],
    facilities: ['Computer Lab', 'Student Lounge', 'Beach Access', 'Outdoor Activities'],
    visa_difficulty: 'difficult',
    part_time_work_allowed: false,
    pathway_programs: false,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'ec-miami',
    name: 'EC English Miami',
    country: 'United States',
    city: 'Miami',
    programs: ['General English', 'Intensive English', 'TOEFL Prep', 'Business English'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 390,
    accommodation_weekly: 330,
    rating: 4.5,
    class_size_max: 15,
    accreditations: ['ACCET', 'English USA'],
    facilities: ['Computer Lab', 'Student Lounge', 'Rooftop Terrace', 'Free WiFi'],
    visa_difficulty: 'difficult',
    part_time_work_allowed: false,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'sprachcaffe-london',
    name: 'Sprachcaffe London',
    country: 'United Kingdom',
    city: 'London',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Business English'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 340,
    accommodation_weekly: 260,
    rating: 4.2,
    class_size_max: 14,
    accreditations: ['British Council', 'English UK'],
    facilities: ['Computer Lab', 'Student Lounge', 'Garden', 'Free WiFi'],
    visa_difficulty: 'moderate',
    part_time_work_allowed: false,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'ec-toronto',
    name: 'EC English Toronto',
    country: 'Canada',
    city: 'Toronto',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Business English', 'University Pathway'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 330,
    accommodation_weekly: 230,
    rating: 4.5,
    class_size_max: 15,
    accreditations: ['Languages Canada'],
    facilities: ['Computer Lab', 'Student Lounge', 'Kitchen', 'Free WiFi'],
    visa_difficulty: 'easy',
    part_time_work_allowed: true,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'oxford-house-london',
    name: 'Oxford House College London',
    country: 'United Kingdom',
    city: 'London',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Cambridge Exam Prep', 'Business English'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 280,
    accommodation_weekly: 220,
    rating: 4.3,
    class_size_max: 14,
    accreditations: ['British Council', 'English UK'],
    facilities: ['Computer Lab', 'Student Lounge', 'Library', 'Free WiFi'],
    visa_difficulty: 'moderate',
    part_time_work_allowed: false,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'kaplan-edinburgh',
    name: 'Kaplan International - Edinburgh',
    country: 'United Kingdom',
    city: 'Edinburgh',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Business English'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 310,
    accommodation_weekly: 200,
    rating: 4.6,
    class_size_max: 15,
    accreditations: ['British Council', 'English UK'],
    facilities: ['Computer Lab', 'Student Lounge', 'Library', 'Free WiFi'],
    visa_difficulty: 'moderate',
    part_time_work_allowed: false,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'lsi-brisbane',
    name: 'LSI Brisbane',
    country: 'Australia',
    city: 'Brisbane',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Cambridge Exam Prep'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 290,
    accommodation_weekly: 220,
    rating: 4.3,
    class_size_max: 15,
    accreditations: ['NEAS', 'English Australia'],
    facilities: ['Computer Lab', 'Student Lounge', 'Kitchen', 'Free WiFi'],
    visa_difficulty: 'moderate',
    part_time_work_allowed: true,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'ih-belfast',
    name: 'International House Belfast',
    country: 'United Kingdom',
    city: 'Belfast',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Cambridge Exam Prep'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 260,
    accommodation_weekly: 170,
    rating: 4.4,
    class_size_max: 12,
    accreditations: ['British Council', 'English UK'],
    facilities: ['Computer Lab', 'Student Lounge', 'Library', 'Free WiFi'],
    visa_difficulty: 'moderate',
    part_time_work_allowed: false,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  },
  {
    id: 'ec-montreal',
    name: 'EC English Montreal',
    country: 'Canada',
    city: 'Montreal',
    programs: ['General English', 'Academic English', 'IELTS Prep', 'Business English', 'French Language'],
    duration_weeks_min: 1,
    duration_weeks_max: 52,
    weekly_cost: 300,
    accommodation_weekly: 210,
    rating: 4.4,
    class_size_max: 15,
    accreditations: ['Languages Canada'],
    facilities: ['Computer Lab', 'Student Lounge', 'Kitchen', 'Free WiFi'],
    visa_difficulty: 'easy',
    part_time_work_allowed: true,
    pathway_programs: true,
    scholarship_available: false,
    age_min: 16
  }
];
